# Generated by Django 5.0.1 on 2024-01-30 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Listing",
        ),
    ]
