# Generated by Django 5.0.1 on 2024-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_delete_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("text_description", models.CharField(max_length=2000)),
                ("starting_bid", models.FloatField()),
                ("image_url", models.CharField(blank=True, max_length=2000)),
                ("category", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
