# Generated by Django 5.0.1 on 2024-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bid",
            field=models.FloatField(default=0.0),
        ),
    ]
