# Generated by Django 5.0.1 on 2024-02-05 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="numberOfBids",
        ),
    ]
