# Generated by Django 5.0.1 on 2024-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_remove_bid_numberofbids"),
    ]

    operations = [
        migrations.CreateModel(
            name="watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listings",
                    models.ManyToManyField(
                        blank=True, related_name="watchlists", to="auctions.listing"
                    ),
                ),
            ],
        ),
    ]
