# Generated by Django 5.0.1 on 2024-02-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_listing_lastbidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
