# Generated by Django 5.0.1 on 2024-02-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_comments_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="Comment",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
