# Generated by Django 5.0.1 on 2024-02-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_alter_comments_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catergory_name", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
    ]
